{{- if .Values.global.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yashigani-gateway-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yashigani-gateway
      app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yashigani-backoffice-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yashigani-backoffice
      app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: yashigani-policy-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yashigani-policy
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
