apiVersion: v1
kind: Service
metadata:
  name: yashigani-backoffice
  namespace: {{ .Release.Namespace }}
  labels:
    app: yashigani-backoffice
    app.kubernetes.io/name: yashigani-backoffice
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: yashigani-backoffice
  ports:
    - name: https
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8443
