#!/usr/bin/env bash
# scripts/offboard.sh — yashigani offboard <agent-name>
#
# Reverses the codegen output for a named onboarded agent:
#   1. Removes the service_identities.yaml entry (sentinel-guarded)
#   2. Removes the pki_ownership.sh tuple (sentinel-guarded, via Python rewriter)
#   3. Removes the Caddy include LINE from docker/caddy/agents/ (include line only —
#      does NOT restructure Caddyfile internals; S4 sentinel-insert is Captain's scope)
#   4. Removes the compose override stanza (docker/<agent>-compose.override.yml)
#   5. Wipes secrets/certs: <agent>_client.{key,crt}
#   6. Triggers _pki_run_issuer rotate-leaves to rotate remaining service leaves
#   7. Removes the Helm values block (values-<agent>.yaml + networkpolicy overlay)
#   8. Writes an offboard ledger entry (docker/var/offboard-ledger.log)
#
# Each step is idempotent — safe to re-run if a previous run was interrupted.
#
# S4 TODO (Captain scope): Caddyfile sentinel-insert/remove for the import line
# lives in the Captain parallel branch (feat/p1-w3p2a-caddy-hardening). This
# script removes the include FILE (agents/<agent>.caddy) and the import LINE
# within whichever Caddyfile contains it, using an exact-string match. Do NOT
# restructure Caddyfile blocks or change the surrounding block layout.
#
# Security:
#   - Three-tier file removal: direct → podman unshare → ephemeral container
#     (mirrors uninstall.sh pattern, avoid EPERM on UID-remapped secrets)
#   - Never uses sed -i (BSD/GNU portability trap)
#   - Fail-closed: any required step failing exits non-zero
#   - Idempotent: re-running after partial completion is safe
#
# Usage:
#   ./scripts/offboard.sh <agent-name>
#   YSG_RUNTIME=docker ./scripts/offboard.sh my-agent
#   YSG_DRY_RUN=true ./scripts/offboard.sh my-agent
#
# Requirements:
#   - Run from the repo root (or WORK_DIR set)
#   - install.sh must have been run previously (WORK_DIR must exist)
#   - python3 available for lib/pki_ownership_append.py calls
#
# Bash 3.2 compatibility: no declare -A, no ${var,,}, no mapfile.
#
# Last updated: 2026-05-29T00:00:00+00:00 (feat(p1-w4): S5 yashigani offboard command)
# ---------------------------------------------------------------------------

set -euo pipefail
IFS=$(printf '\n\t')

# Hardened PATH — never trust inherited PATH for privileged scripts.
PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/opt/podman/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH

# ---------------------------------------------------------------------------
# Globals
# ---------------------------------------------------------------------------
_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
_REPO_ROOT="$(cd "${_SCRIPT_DIR}/.." && pwd)"

WORK_DIR="${WORK_DIR:-${_REPO_ROOT}}"
YSG_RUNTIME="${YSG_RUNTIME:-}"
YSG_DRY_RUN="${YSG_DRY_RUN:-false}"

# Alpine image for ephemeral-container tier (digest-pinned, same as install.sh).
_ALPINE_IMAGE="alpine:3@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11"

# ---------------------------------------------------------------------------
# Logging helpers (mirror install.sh style)
# ---------------------------------------------------------------------------
_log_info()  { printf "  [offboard] %s\n"        "$*"; }
_log_warn()  { printf "  [offboard] WARN: %s\n"  "$*" >&2; }
_log_error() { printf "  [offboard] ERROR: %s\n" "$*" >&2; }
_log_step()  { printf "\n  [offboard] ── %s\n"   "$*"; }
_dry_print() {
  if [[ "${YSG_DRY_RUN:-false}" == "true" ]]; then
    printf "  [DRY-RUN] %s\n" "$*"
    return 0
  fi
  return 1  # not dry run — caller should execute the real command
}

# ---------------------------------------------------------------------------
# _offboard_usage
# ---------------------------------------------------------------------------
_offboard_usage() {
  cat >&2 <<'USAGE'
Usage: scripts/offboard.sh <agent-name>

  Removes all artifacts generated by `yashigani onboard` for the named agent:
    service_identities.yaml entry, pki_ownership.sh tuple, Caddy snippet,
    compose override, certs/keys, Helm values, and writes an offboard ledger entry.

Options (env vars):
  YSG_RUNTIME=docker|podman    — override runtime detection
  YSG_DRY_RUN=true             — print actions without executing
  WORK_DIR=/path/to/repo       — override repo root

USAGE
  exit 1
}

# ---------------------------------------------------------------------------
# _validate_agent_name — reject names that do not match the onboard slug.
#
# F2: align to the W3 onboard slug ^[a-z0-9][a-z0-9\-]{0,62}[a-z0-9]$
# (lowercase, no underscore, min-2 chars, max-64 chars, no leading/trailing
# hyphen).  Any name that passed onboard validation is accepted here; any
# name that would have been rejected by onboard is also rejected here.
# ---------------------------------------------------------------------------
_validate_agent_name() {
  local _name="$1"
  # Slug must be 2-64 chars, lowercase alphanumeric + interior hyphens only.
  if ! printf '%s' "$_name" | grep -qE '^[a-z0-9][a-z0-9-]{0,62}[a-z0-9]$'; then
    _log_error "agent name '${_name}' is not a valid yashigani slug."
    _log_error "  Required: ^[a-z0-9][a-z0-9-]{0,62}[a-z0-9]$ (lowercase, no underscore,"
    _log_error "  no leading/trailing hyphen, 2-64 characters)."
    return 1
  fi
}

# ---------------------------------------------------------------------------
# _detect_runtime — resolve YSG_RUNTIME if not set
# Source W2 detect_runtime.sh if available; fall back to legacy YSG_RUNTIME.
# ---------------------------------------------------------------------------
_offboard_detect_runtime() {
  if [[ -n "${YSG_RUNTIME:-}" ]]; then
    _log_info "Runtime: ${YSG_RUNTIME} (explicit)"
    return 0
  fi
  # Source W2 detect_runtime.sh for 4-way detection
  local _dr_sh="${_REPO_ROOT}/lib/detect_runtime.sh"
  if [[ -f "$_dr_sh" ]]; then
    # shellcheck source=lib/detect_runtime.sh
    # shellcheck disable=SC1091
    . "$_dr_sh"
    _detect_runtime 2>/dev/null || true
    case "${YSG_RUNTIME_4WAY:-unknown}" in
      docker)           YSG_RUNTIME="docker" ;;
      podman-rootful)   YSG_RUNTIME="podman" ;;
      podman-rootless)  YSG_RUNTIME="podman" ;;
      k8s)              YSG_RUNTIME="k8s"    ;;
      *)
        _log_warn "Could not detect runtime — defaulting to docker. Set YSG_RUNTIME explicitly."
        YSG_RUNTIME="docker"
        ;;
    esac
  else
    _log_warn "lib/detect_runtime.sh not found — defaulting to docker."
    YSG_RUNTIME="docker"
  fi
  _log_info "Runtime detected: ${YSG_RUNTIME} (YSG_RUNTIME_4WAY=${YSG_RUNTIME_4WAY:-n/a})"
}

# ---------------------------------------------------------------------------
# _runtime_cmd — return the container runtime command name
# ---------------------------------------------------------------------------
_offboard_runtime_cmd() {
  case "${YSG_RUNTIME:-docker}" in
    podman) printf 'podman' ;;
    docker) printf 'docker' ;;
    k8s)    printf 'kubectl' ;;
    *)      printf 'docker' ;;
  esac
}

# ---------------------------------------------------------------------------
# _three_tier_rm — remove a file with three-tier fallback
#   Tier 1: direct rm (same-user / root caller)
#   Tier 2: podman unshare rm (rootless Podman path)
#   Tier 3: ephemeral container rm (Docker or Podman remote)
#
# Usage: _three_tier_rm <file-path>
# Returns: 0 on success, 1 on total failure
# ---------------------------------------------------------------------------
_three_tier_rm() {
  local _target="$1"
  if [[ ! -e "$_target" ]]; then
    _log_info "  (already absent: ${_target})"
    return 0
  fi

  if _dry_print "rm -f ${_target}"; then
    return 0
  fi

  # Tier 1: direct
  if rm -f "$_target" 2>/dev/null; then
    _log_info "  [removed tier-1] ${_target}"
    return 0
  fi

  _log_warn "  direct rm failed for ${_target} — trying tier-2 (podman unshare)"

  # Tier 2: podman unshare (rootless Podman path)
  if command -v podman >/dev/null 2>&1; then
    if podman unshare rm -f "$_target" 2>/dev/null; then
      _log_info "  [removed tier-2] ${_target} (podman unshare)"
      return 0
    fi
    _log_warn "  podman unshare rm failed — trying tier-3 (ephemeral container)"
  fi

  # Tier 3: ephemeral container
  local _runtime
  _runtime="$(_offboard_runtime_cmd)"
  local _parent
  _parent="$(dirname "$_target")"
  local _basename
  _basename="$(basename "$_target")"
  if "${_runtime}" run --rm \
      -v "${_parent}:/t:rw,Z" \
      "$_ALPINE_IMAGE" rm -f "/t/${_basename}" 2>/dev/null; then
    _log_info "  [removed tier-3] ${_target} (ephemeral container)"
    return 0
  fi

  _log_error "  All three removal tiers failed for: ${_target}"
  _log_error "  Manual cleanup required:"
  _log_error "    rm -f '${_target}'"
  _log_error "    OR: podman unshare rm -f '${_target}'"
  return 1
}

# ---------------------------------------------------------------------------
# Step 1: Remove service_identities.yaml entry
# The entry is bracketed by sentinel comments:
#   # BEGIN YSG-ONBOARD-<agent>
#   ...
#   # END YSG-ONBOARD-<agent>
# Uses Python rewriter (same approach as lib/pki_ownership_append.py)
# to avoid BSD vs GNU sed portability issues.
# ---------------------------------------------------------------------------
_offboard_step1_service_identity() {
  local _agent="$1"
  local _sid_file="${WORK_DIR}/docker/service_identities.yaml"
  _log_step "1/8 Remove service_identities.yaml entry for '${_agent}'"

  if [[ ! -f "$_sid_file" ]]; then
    _log_warn "  service_identities.yaml not found at ${_sid_file} — skipping"
    return 0
  fi

  # Check if an onboarded entry exists
  local _begin_marker="# BEGIN YSG-ONBOARD-${_agent}"
  if ! grep -qF "$_begin_marker" "$_sid_file" 2>/dev/null; then
    _log_info "  No sentinel entry for '${_agent}' in service_identities.yaml — already clean"
    return 0
  fi

  if _dry_print "python3: remove sentinel block for '${_agent}' from ${_sid_file}"; then
    return 0
  fi

  # Python rewriter — removes the sentinel-bracketed block
  # F-Laura (LAURA-P1W4-001): anchored line-regex, not str.find() substring,
  # so 'letta' does NOT match 'letta-pgbouncer'.
  python3 - "$_sid_file" "$_agent" <<'PYEOF'
import sys, re, os, tempfile
sid_file = sys.argv[1]
agent    = sys.argv[2]
content  = open(sid_file, encoding='utf-8').read()
esc     = re.escape(agent)
begin_re = re.compile(r'^[ \t]*# BEGIN YSG-ONBOARD-' + esc + r'[ \t]*$', re.MULTILINE)
end_re   = re.compile(r'^[ \t]*# END YSG-ONBOARD-'   + esc + r'[ \t]*$', re.MULTILINE)
bm = begin_re.search(content)
if bm is None:
    sys.exit(0)  # already absent
line_start = bm.start()
em = end_re.search(content, bm.start())
if em is None:
    print('[offboard] WARNING: BEGIN sentinel found but no END — removing from BEGIN to EOF', file=sys.stderr)
    new_content = content[:line_start]
else:
    end_line = content.find('\n', em.end())
    end_line = (end_line + 1) if end_line != -1 else len(content)
    new_content = content[:line_start] + content[end_line:]
# Atomic write
dir_ = os.path.dirname(sid_file) or '.'
fd, tmp = tempfile.mkstemp(dir=dir_, prefix='.ysg-offboard-tmp-', suffix='.yaml')
try:
    os.write(fd, new_content.encode('utf-8'))
    os.close(fd); fd = -1
    os.chmod(tmp, os.stat(sid_file).st_mode & 0o777)
    os.rename(tmp, sid_file)
except Exception:
    if fd != -1:
        os.close(fd)
    os.unlink(tmp)
    raise
PYEOF
  _log_info "  Removed service_identities.yaml entry for '${_agent}'"
}

# ---------------------------------------------------------------------------
# Step 2: Remove pki_ownership.sh tuple (via Python appender)
# ---------------------------------------------------------------------------
_offboard_step2_pki_ownership() {
  local _agent="$1"
  local _pki_sh="${WORK_DIR}/lib/pki_ownership.sh"
  local _appender="${WORK_DIR}/lib/pki_ownership_append.py"
  _log_step "2/8 Remove pki_ownership.sh tuple for '${_agent}'"

  if [[ ! -f "$_pki_sh" ]]; then
    _log_warn "  lib/pki_ownership.sh not found at ${_pki_sh} — skipping"
    return 0
  fi

  if [[ ! -f "$_appender" ]]; then
    _log_warn "  lib/pki_ownership_append.py not found — falling back to inline removal"
    # Inline Python fallback (same logic as appender remove).
    # F-Laura (LAURA-P1W4-001): anchored regex, not str.find().
    # F3: reject inline (non-sentinel) entries with exit 1, matching
    #     the primary path's behaviour (core services must not be removed).
    local _fallback_rc=0
    python3 - "$_pki_sh" "$_agent" <<'PYEOF' || _fallback_rc=$?
import sys, re, os, tempfile
pki_file = sys.argv[1]
agent    = sys.argv[2]
content  = open(pki_file, encoding='utf-8').read()
esc      = re.escape(agent)
begin_re = re.compile(r'^[ \t]*# BEGIN YSG-ONBOARD-' + esc + r'[ \t]*$', re.MULTILINE)
end_re   = re.compile(r'^[ \t]*# END YSG-ONBOARD-'   + esc + r'[ \t]*$', re.MULTILINE)
bm = begin_re.search(content)
if bm is None:
    # F3: check for an inline (non-sentinel) entry — refuse to remove core services.
    inline_re = re.compile(r'"' + esc + r':\d+:0\d{3}"')
    if inline_re.search(content):
        print('[offboard] ERROR: service %r has an inline entry (not sentinel-managed). '
              'Core services cannot be removed via offboard. '
              'Remove manually if this is intentional.' % agent, file=sys.stderr)
        sys.exit(1)
    sys.exit(0)  # not found — idempotent
line_start = bm.start()
em = end_re.search(content, bm.start())
if em is None:
    sys.exit(0)
end_line = content.find('\n', em.end())
end_line = (end_line + 1) if end_line != -1 else len(content)
new_content = content[:line_start] + content[end_line:]
dir_ = os.path.dirname(pki_file) or '.'
fd, tmp = tempfile.mkstemp(dir=dir_, prefix='.ysg-offboard-tmp-', suffix='.sh')
try:
    os.write(fd, new_content.encode('utf-8'))
    os.close(fd); fd = -1
    os.chmod(tmp, os.stat(pki_file).st_mode & 0o777)
    os.rename(tmp, pki_file)
except Exception:
    if fd != -1: os.close(fd)
    os.unlink(tmp)
    raise
PYEOF
    if [[ "$_fallback_rc" -ne 0 ]]; then
      _log_error "  Inline PKI removal failed (rc=${_fallback_rc}) — see stderr above"
      return 1
    fi
    _log_info "  Removed pki_ownership.sh tuple for '${_agent}' (inline fallback)"
    return 0
  fi

  if _dry_print "python3 lib/pki_ownership_append.py remove --service ${_agent} --lib ${_pki_sh}"; then
    return 0
  fi

  local _rc=0
  python3 "$_appender" remove --service "$_agent" --lib "$_pki_sh" || _rc=$?
  case "$_rc" in
    0|2|3)
      _log_info "  pki_ownership.sh tuple removed (or already absent) for '${_agent}'"
      ;;
    *)
      _log_error "  pki_ownership_append.py remove failed (rc=${_rc})"
      return 1
      ;;
  esac
}

# ---------------------------------------------------------------------------
# Step 3: Remove Caddy snippet FILE
#
# W3-P2a coordination (F1): the merged W3-P2a branch uses a single wildcard
# glob `import /etc/caddy/agents/*.caddy` in the Caddyfiles (NOT per-agent
# import lines).  Removing the snippet FILE is sufficient — Caddy stops
# loading it on the next reload because the glob no longer matches.
# Do NOT attempt to edit Caddyfile import lines; the glob handles loading
# automatically.  Any pre-W3-P2a per-agent import lines are the Captain's
# migration scope (feat/p1-w3p2a-caddy-hardening).
# ---------------------------------------------------------------------------
_offboard_step3_caddy_snippet() {
  local _agent="$1"
  local _caddy_dir="${WORK_DIR}/docker/caddy"
  local _snippet="${_caddy_dir}/agents/${_agent}.caddy"
  _log_step "3/8 Remove Caddy snippet file for '${_agent}'"

  # Remove the snippet file — the W3-P2a wildcard glob stops loading it automatically.
  if [[ -f "$_snippet" ]]; then
    if _dry_print "rm ${_snippet}"; then :; else
      _three_tier_rm "$_snippet" || true
      _log_info "  Removed Caddy snippet: ${_snippet}"
      _log_info "  (W3-P2a wildcard glob will stop loading it on next Caddy reload)"
    fi
  else
    _log_info "  Caddy snippet not present: ${_snippet} — already clean"
  fi
  # The Caddyfile itself is NOT modified — the glob import is managed by W3-P2a.
}

# ---------------------------------------------------------------------------
# Step 4: Remove compose override stanza
# docker/<agent>-compose.override.yml
# ---------------------------------------------------------------------------
_offboard_step4_compose_override() {
  local _agent="$1"
  local _override="${WORK_DIR}/docker/${_agent}-compose.override.yml"
  _log_step "4/8 Remove compose override for '${_agent}'"

  if [[ ! -f "$_override" ]]; then
    _log_info "  Compose override not present: ${_override}"
    return 0
  fi

  if _dry_print "rm ${_override}"; then
    return 0
  fi

  _three_tier_rm "$_override" || return 1
  _log_info "  Removed compose override: ${_override}"
}

# ---------------------------------------------------------------------------
# Step 5: Remove secrets and certs
# <agent>_client.key, <agent>_client.crt, <agent>_bootstrap_token
# ---------------------------------------------------------------------------
_offboard_step5_secrets() {
  local _agent="$1"
  local _secrets_dir="${WORK_DIR}/docker/secrets"
  _log_step "5/8 Remove secrets/certs for '${_agent}'"

  local _removed=0
  for _f in \
      "${_secrets_dir}/${_agent}_client.key" \
      "${_secrets_dir}/${_agent}_client.crt" \
      "${_secrets_dir}/${_agent}_bootstrap_token"; do
    if [[ -f "$_f" ]]; then
      if _dry_print "rm ${_f}"; then :; else
        _three_tier_rm "$_f" && _removed=$((_removed + 1)) || true
      fi
    fi
  done

  if [[ "$_removed" -gt 0 ]]; then
    _log_info "  Removed ${_removed} secret/cert file(s) for '${_agent}'"
  else
    _log_info "  No secret/cert files found for '${_agent}' — already clean"
  fi
}

# ---------------------------------------------------------------------------
# Step 6: Trigger PKI rotate-leaves
# So the remaining services get fresh leaves that no longer include the removed service.
#
# C-002 (Nico+Iris): rotate-leaves failure is now a distinct ERROR so operators
# see it in alerting.  Offboard is still re-runnable (idempotent), but the
# failure is surfaced loudly rather than silently continuing.
#
# K8s gap (C-002): the mtls-bootstrap-job runs on `helm install` / `helm upgrade`
# only — it does NOT trigger automatically on offboard.  Operators must run a
# `helm upgrade` (which triggers the job and calls rotate-leaves via the
# upgrade-mode sentinel) after offboarding to rotate leaves on K8s.
# This is documented here and in the step output so operators cannot miss it.
# ---------------------------------------------------------------------------
_offboard_step6_pki_rotate() {
  local _agent="$1"
  _log_step "6/8 PKI rotate-leaves (remove '${_agent}' from leaf issuance)"

  if [[ "${YSG_RUNTIME:-docker}" == "k8s" ]]; then
    _log_info "  K8s runtime detected."
    _log_info ""
    _log_info "  C-002 OPERATOR ACTION REQUIRED:"
    _log_info "  The mtls-bootstrap-job does NOT trigger automatically on offboard."
    _log_info "  You MUST run a helm upgrade to rotate leaves and close the dangling-leaf gap:"
    _log_info "    helm upgrade yashigani helm/yashigani -n <namespace> -f <values>"
    _log_info "  The upgrade triggers the bootstrap job in rotate-leaves mode."
    _log_info "  Until the upgrade completes, the offboarded agent's leaf cert is still"
    _log_info "  valid — this is a known K8s gap (no on-demand rotation without helm upgrade)."
    return 0
  fi

  if _dry_print "install.sh --pki-action=rotate-leaves (triggered by offboard)"; then
    return 0
  fi

  local _install_sh="${WORK_DIR}/install.sh"
  if [[ ! -f "$_install_sh" ]]; then
    _log_warn "  install.sh not found at ${_install_sh} — skipping PKI rotate-leaves"
    _log_warn "  Run manually: ./install.sh --pki-action=rotate-leaves"
    return 0
  fi

  # Call install.sh as a subprocess with --pki-action to avoid side-effects.
  # YSG_RUNTIME is passed through so the right runtime is used.
  local _rc=0
  YSG_RUNTIME="${YSG_RUNTIME:-docker}" \
  YSG_NO_LOG=true \
    bash "$_install_sh" --pki-action rotate-leaves 2>&1 | \
    while IFS= read -r _line; do
      _log_info "  pki: ${_line}"
    done || _rc=$?
  if [[ "$_rc" -ne 0 ]]; then
    # C-002: promote to ERROR so alerting / operators see this.
    # The offboarded agent's identity is already removed from service_identities.yaml
    # and pki_ownership.sh, but cert rotation failed — the deprovisioned agent's
    # leaf cert is still technically valid until it expires.  This is a dangling-leaf
    # risk.  Offboard is still re-runnable (steps 1-5 are idempotent); operator must
    # re-run or run install.sh --pki-action=rotate-leaves manually.
    _log_error "  C-002 PKI rotate-leaves FAILED (rc=${_rc})."
    _log_error "  DANGLING-LEAF RISK: the offboarded agent's leaf cert may still be valid."
    _log_error "  Re-run offboard or rotate manually before completing deprovisioning:"
    _log_error "    ./install.sh --pki-action=rotate-leaves"
    return 1  # fatal: caller must not suppress this failure
  fi
  _log_info "  PKI rotate-leaves completed"
}

# ---------------------------------------------------------------------------
# Step 7: Remove Helm values + codegen artifacts
#
# F1 (Iris BLOCKING): the W3 codegen emits three additional files that the
# original step 7 did not remove:
#   opa/<agent>.rego               — OPA policy stub (WORST omission: an
#                                    orphaned stub means the ring-fence policy
#                                    is NOT removed for a deprovisioned agent)
#   tests/contracts/test_<agent>_compose.py
#   tests/contracts/test_<agent>_helm.py
#
# All six artifact paths are removed here in the same idempotent rm-or-skip
# pattern.
# ---------------------------------------------------------------------------
_offboard_step7_helm() {
  local _agent="$1"
  local _helm_dir="${WORK_DIR}/helm/yashigani"
  _log_step "7/8 Remove Helm values + codegen artifacts for '${_agent}'"

  local _removed=0
  for _f in \
      "${_helm_dir}/values-${_agent}.yaml" \
      "${_helm_dir}/values-${_agent}-networkpolicy.yaml" \
      "${_helm_dir}/templates/agents/${_agent}-policy-exception.yaml" \
      "${WORK_DIR}/opa/${_agent}.rego" \
      "${WORK_DIR}/tests/contracts/test_${_agent}_compose.py" \
      "${WORK_DIR}/tests/contracts/test_${_agent}_helm.py"; do
    if [[ -f "$_f" ]]; then
      if _dry_print "rm ${_f}"; then :; else
        if rm -f "$_f" 2>/dev/null; then
          _removed=$((_removed + 1))
          _log_info "  [removed] ${_f}"
        else
          _log_warn "  Could not remove ${_f} — manual cleanup needed"
        fi
      fi
    fi
  done

  if [[ "$_removed" -gt 0 ]]; then
    _log_info "  Removed ${_removed} Helm/codegen artifact(s) for '${_agent}'"
  else
    _log_info "  No Helm/codegen artifacts found for '${_agent}' — already clean"
  fi
}

# ---------------------------------------------------------------------------
# Step 8: Write offboard ledger entry
# docker/var/offboard-ledger.log (gitignored)
# Format: ISO-8601 timestamp | agent | operator-uid | operator-user | runtime
# ---------------------------------------------------------------------------
_offboard_step8_ledger() {
  local _agent="$1"
  local _ledger_dir="${WORK_DIR}/docker/var"
  local _ledger_file="${_ledger_dir}/offboard-ledger.log"
  _log_step "8/8 Write offboard ledger and MANIFEST_OFFBOARD audit event"

  if _dry_print "ledger: offboard ${_agent} @ $(date -u +%Y-%m-%dT%H:%M:%SZ)"; then
    return 0
  fi

  mkdir -p "$_ledger_dir" 2>/dev/null || true

  local _ts
  _ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  local _uid
  _uid="$(id -u 2>/dev/null || printf 'unknown')"
  local _user
  _user="$(id -un 2>/dev/null || printf 'unknown')"

  printf '%s | agent=%s | uid=%s | user=%s | runtime=%s\n' \
      "$_ts" "$_agent" "$_uid" "$_user" "${YSG_RUNTIME:-unknown}" \
      >> "$_ledger_file" 2>/dev/null || true
  chmod 0640 "$_ledger_file" 2>/dev/null || true

  _log_info "  Ledger entry written: ${_ledger_file}"

  # G2 stage-6a: emit MANIFEST_OFFBOARD Merkle audit event (Lu-Gap-06 / G2.2).
  # Operator identity is read from YSG_OPERATOR_IDENTITY env var, set by the
  # step-up gate in install.sh before _username is cleared. Unset on fresh
  # installs (no running system) — falls back to os user.
  _offboard_emit_merkle_event "$_agent" "$_ts" "$_uid" "$_user"
}

# ---------------------------------------------------------------------------
# _offboard_emit_merkle_event — G2 stage-6a MANIFEST_OFFBOARD audit event
#
# Belt-and-suspenders: called from _offboard_step8_ledger after all
# artifact removals succeed. Failure logs a warning but does NOT abort
# (all artifact removals are already durable).
#
# The artifacts_removed list mirrors the eight offboard steps.
# cert_rotation_triggered is always true: step 6 runs rotate-leaves.
# ---------------------------------------------------------------------------
_offboard_emit_merkle_event() {
  local _agent="$1"
  local _ts="$2"
  local _uid="$3"
  local _user="$4"

  if _dry_print "merkle-audit: MANIFEST_OFFBOARD for ${_agent}"; then
    return 0
  fi

  # Resolve Python path (same approach as install.sh codegen heredoc)
  local _src_dir="${WORK_DIR}/src"
  local _operator="${YSG_OPERATOR_IDENTITY:-}"
  if [[ -z "$_operator" ]]; then
    _operator="${_user}@local (uid=${_uid}, no step-up)"
  fi
  local _audit_log_path="${YASHIGANI_AUDIT_LOG_PATH:-${WORK_DIR}/docker/var/audit.log}"

  local _merkle_rc=0
  python3 - "$_agent" "$_src_dir" "$_operator" "$_audit_log_path" \
      "${YSG_RUNTIME:-unknown}" <<'OFFBOARD_PYEOF' || _merkle_rc=$?

import sys, os

agent_name     = sys.argv[1]
src_dir        = sys.argv[2]
operator       = sys.argv[3]
audit_log_path = sys.argv[4]
runtime        = sys.argv[5]

if src_dir not in sys.path:
    sys.path.insert(0, src_dir)

try:
    from yashigani.audit.writer import AuditLogWriter
    from yashigani.audit.config import AuditConfig
    from yashigani.audit.schema import ManifestOffboardEvent
except ImportError as e:
    # FIX-03: LOUD import failure — operator must see this.
    print('', file=sys.stderr)
    print('[offboard] ERROR: cannot import audit package — MANIFEST_OFFBOARD will NOT be written.', file=sys.stderr)
    print('[offboard] ERROR: Cause: %s' % e, file=sys.stderr)
    print('[offboard] ERROR: Agent=%s  Operator=%s' % (agent_name, operator), file=sys.stderr)
    sys.exit(1)  # non-fatal at shell level (caught by ||)

# artifacts_removed: labels for the eight offboard steps
_artifacts_removed = [
    'service_identities.yaml entry',
    'pki_ownership.sh tuple',
    'caddy snippet',
    'compose override',
    'secrets/certs',
    'pki rotate-leaves',
    'helm values',
    'offboard ledger',
]

try:
    _config = AuditConfig(
        log_path=audit_log_path,
        max_file_size_mb=int(os.environ.get('YASHIGANI_AUDIT_MAX_FILE_SIZE_MB', '100')),
        retention_days=int(os.environ.get('YASHIGANI_AUDIT_RETENTION_DAYS', '90')),
    )
    _writer = AuditLogWriter(config=_config)
    _writer.write(ManifestOffboardEvent(
        agent_name=agent_name,
        operator_identity=operator,
        artifacts_removed=_artifacts_removed,
        cert_rotation_triggered=True,
    ))
    _writer.close()
    print('[offboard] MANIFEST_OFFBOARD audit event written (operator=%s)' % operator)
except Exception as _audit_exc:
    # FIX-03: LOUD failure — operator/auditor must see the missing Merkle record.
    print('', file=sys.stderr)
    print('[offboard] ERROR: MANIFEST_OFFBOARD audit event write FAILED', file=sys.stderr)
    print('[offboard] ERROR: Agent=%s  Operator=%s' % (agent_name, operator), file=sys.stderr)
    print('[offboard] ERROR: Cause: %s' % _audit_exc, file=sys.stderr)
    print('[offboard] ERROR: Investigate audit volume and add record manually.', file=sys.stderr)
    sys.exit(1)  # non-fatal at shell level (_merkle_rc captures exit code)
OFFBOARD_PYEOF
  # FIX-03 (YCS-...-W6-03): OFFBOARD audit-write failure stays non-fatal
  # (rollback must not be blocked) but must be LOUD so operator and auditor
  # see the missing Merkle record.
  if [[ "$_merkle_rc" -ne 0 ]]; then
    _log_warn "=========================================="
    _log_warn "  MANIFEST_OFFBOARD audit event write FAILED"
    _log_warn "  The offboard artifacts were removed but the"
    _log_warn "  Merkle audit record could NOT be written."
    _log_warn "  Investigate the audit volume and add a"
    _log_warn "  MANIFEST_OFFBOARD record manually."
    _log_warn "=========================================="
  fi
}

# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
main() {
  if [[ $# -lt 1 ]]; then
    _offboard_usage
  fi

  local _agent="$1"

  # Validate name before any filesystem operations
  _validate_agent_name "$_agent" || exit 1

  _log_info "=== yashigani offboard: agent='${_agent}' ==="
  if [[ "${YSG_DRY_RUN:-false}" == "true" ]]; then
    _log_info "=== DRY RUN MODE — no changes will be made ==="
  fi

  # Resolve runtime
  _offboard_detect_runtime

  _log_info "  WORK_DIR=${WORK_DIR}"
  _log_info "  YSG_RUNTIME=${YSG_RUNTIME}"

  # Validate WORK_DIR is a yashigani repo root
  if [[ ! -f "${WORK_DIR}/install.sh" ]]; then
    _log_error "WORK_DIR '${WORK_DIR}' does not look like a yashigani repo root (install.sh not found)."
    _log_error "Set WORK_DIR=/path/to/yashigani or run from the repo root."
    exit 1
  fi

  # Execute all steps. Non-fatal steps continue on error; fatal steps exit.
  _offboard_step1_service_identity "$_agent"  || { _log_error "Step 1 failed"; exit 1; }
  _offboard_step2_pki_ownership    "$_agent"  || { _log_error "Step 2 failed"; exit 1; }
  _offboard_step3_caddy_snippet    "$_agent"  # non-fatal: Caddy reload not required
  _offboard_step4_compose_override "$_agent"  || { _log_error "Step 4 failed"; exit 1; }
  _offboard_step5_secrets          "$_agent"  # non-fatal: best-effort cleanup
  _offboard_step6_pki_rotate       "$_agent"  || { _log_error "Step 6 (PKI rotate-leaves) failed — dangling-leaf risk; see above"; exit 1; }
  _offboard_step7_helm             "$_agent"  # non-fatal: Helm files may not exist
  _offboard_step8_ledger           "$_agent"  # non-fatal: ledger is advisory

  printf "\n"
  if [[ "${YSG_DRY_RUN:-false}" == "true" ]]; then
    _log_info "=== DRY RUN complete — no files were modified ==="
  else
    _log_info "=== offboard complete for agent='${_agent}' ==="
    _log_info "  Next steps:"
    _log_info "    1. Restart the stack to pick up the PKI rotation:"
    _log_info "       docker compose restart  (or: podman compose restart)"
    _log_info "    2. Verify no ${_agent} container is running:"
    _log_info "       docker ps | grep ${_agent}"
  fi
}

main "$@"
