replicaCount: 1

image:
  repository: grafana/loki
  tag: "3.0.0"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  size: 10Gi
  storageClass: ""

config:
  existingSecretName: "yashigani-loki-config"
  configKey: "loki.yml"
