enabled: true
image:
  repository: grafana/grafana
  tag: "13.0.1@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a"
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
service:
  port: 3000
  type: ClusterIP
existingSecretName: yashigani-grafana-secrets
adminUser: "grafana-admin"
persistence:
  enabled: true
  size: 5Gi
  storageClass: ""
